/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.0/userguide/multi_project_builds.html
 */

rootProject.name = "kotlin-example-project"
include(
    "app",
    "library",
    "spring",

    "advent-of-code-2020-1",
    "advent-of-code-2020-2",
    "advent-of-code-2020-3",
    "advent-of-code-2020-4",

    "kotlin-delegates",
    "kotlin-pattern-matching",

    "kotlin-obsidian-graph",

    "utils",
)
